package com.foremen.qa.fixtures;

/**
 * A provisioned test user (Requirement 12.4).
 *
 * <p>Carries exactly what later steps need to UI-login as this user and to reference/clean it up:
 * the generated primary key {@code id}, the login {@code email}, the plaintext {@code password}
 * (only ever a generated test credential — never a real one), and the {@code roleCode} the user was
 * created under.
 *
 * @param id       the {@code users.id} generated by the INSERT
 * @param email    the login email (also the {@code otp_tokens} cleanup key)
 * @param password the generated plaintext password used for UI password-login
 * @param roleCode the {@code roles.code} the user holds
 */
public record TestUser(long id, String email, String password, String roleCode) {
}
