package com.foremen.service.signing.merge;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.foremen.dao.model.SignableDocumentEntity;
import com.foremen.exception.ForemenApiException;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import net.jqwik.api.Arbitraries;
import net.jqwik.api.Arbitrary;
import net.jqwik.api.ForAll;
import net.jqwik.api.Property;
import net.jqwik.api.Provide;
import net.jqwik.api.Tag;
import org.springframework.http.HttpStatus;

/**
 * Property-based tests for {@link DefaultTemplateMergeEngine#render(String, MergeContext, MergeMode)}
 * — the pure, plain-string {@code {Token}} merge over an ordered set of {@link MergeFieldResolver}s
 * (FOR-05-08, Requirements 3.3, 3.4, 3.8; design §Components {@code TemplateMergeEngine}, Property 6).
 *
 * <p>The engine is exercised directly against a <b>controllable fake resolver</b> — no Spring
 * context, no persistence. The fake maps a fixed set of known tokens to values, declares a second
 * set of tokens as {@code supported} but resolving to {@code null} (the "supported-but-absent"
 * unresolved path), and claims no other token (the "no supporting resolver" unresolved path).
 * Arbitrary templates are generated by interleaving literal text with placeholders drawn from both
 * the resolvable and the two unresolvable token pools, so every render mixes substituted and
 * unresolved tokens.
 *
 * <p>Feature: FOR-05-08-document-signing, Property 6: merge resolution is deterministic with
 * reported unresolved placeholders.
 *
 * <p><b>Validates: Requirements 3.3, 3.4, 3.8</b>
 */
@Tag("Feature: FOR-05-08-document-signing, Property 6: merge resolution is deterministic with reported unresolved placeholders")
class DefaultTemplateMergeEnginePropertyTest {

    private static final String UNRESOLVED_MESSAGE = "error.document.unresolved.placeholders";
    private static final String BLANK_SENTINEL = "«___»";

    /** Tokens the fake resolver maps to a concrete, non-null value. */
    private static final Map<String, String> RESOLVABLE = Map.of(
            "ContactName", "Jan",
            "ContactLastName", "Kowalski",
            "ContactEmail", "jan@example.com",
            "Begindate", "2026-01-01",
            "Closedate", "2026-06-30",
            "TotalBeforeTax", "12345.67");

    /**
     * Tokens the fake resolver {@code supports} but deliberately resolves to {@code null} — the
     * "supported-but-absent" unresolved path (a resolver whose backing datum is missing).
     */
    private static final Set<String> SUPPORTED_BUT_NULL = Set.of(
            "RequisitePrimaryAddressText", "AssignedName");

    /**
     * Tokens no resolver claims — the "no supporting resolver" unresolved path. These are never in
     * {@link #RESOLVABLE} nor {@link #SUPPORTED_BUT_NULL}.
     */
    private static final List<String> UNSUPPORTED = List.of(
            "UnknownToken", "UfCrm9999999999", "NotAField");

    private final DefaultTemplateMergeEngine engine =
            new DefaultTemplateMergeEngine(List.of(new FakeResolver()));

    // A MergeContext is required by the engine signature; the fake resolver ignores it entirely,
    // so a minimal context over an empty document is sufficient for these pure-merge properties.
    private final MergeContext context =
            MergeContext.builder().document(new SignableDocumentEntity()).build();

    // ------------------------------------------------------------------------------------------
    // Property 6a: determinism — the same (templateBody, context, mode) yields an identical body and
    // an identical unresolved set on every call (MARK_BLANK path, which always returns a result).
    // Validates: Requirements 3.3, 3.4, 3.8
    // ------------------------------------------------------------------------------------------

    @Property(tries = 300)
    @Tag("Feature: FOR-05-08-document-signing, Property 6: merge resolution is deterministic with reported unresolved placeholders")
    void renderIsDeterministicForMarkBlank(@ForAll("templates") Template template) {
        MergeResult first = engine.render(template.body(), context, MergeMode.MARK_BLANK);
        MergeResult second = engine.render(template.body(), context, MergeMode.MARK_BLANK);

        assertThat(second.body()).isEqualTo(first.body());
        assertThat(second.unresolvedPlaceholders())
                .containsExactlyElementsOf(first.unresolvedPlaceholders());
    }

    // ------------------------------------------------------------------------------------------
    // Property 6b: every unresolved token is reported, and only unresolved tokens are reported — the
    // reported set is exactly the set of distinct unresolvable tokens the template actually used
    // (both the "supported-but-null" and the "no-resolver" pools), in first-appearance order.
    // Validates: Requirements 3.4, 3.8
    // ------------------------------------------------------------------------------------------

    @Property(tries = 300)
    @Tag("Feature: FOR-05-08-document-signing, Property 6: merge resolution is deterministic with reported unresolved placeholders")
    void everyUnresolvedTokenIsReportedInFirstAppearanceOrder(@ForAll("templates") Template template) {
        MergeResult result = engine.render(template.body(), context, MergeMode.MARK_BLANK);

        // Independent oracle: the distinct unresolvable tokens the template used, in the order they
        // first appear in the token stream.
        Set<String> expectedUnresolved = new LinkedHashSet<>();
        for (String token : template.tokens()) {
            if (!RESOLVABLE.containsKey(token)) {
                expectedUnresolved.add(token);
            }
        }

        assertThat(result.unresolvedPlaceholders())
                .containsExactlyElementsOf(expectedUnresolved);
        // No resolvable token is ever reported as unresolved.
        assertThat(result.unresolvedPlaceholders()).doesNotContainAnyElementsOf(RESOLVABLE.keySet());
    }

    // ------------------------------------------------------------------------------------------
    // Property 6c: resolved tokens are substituted with their value and are NEVER left as a blank
    // sentinel; unresolved tokens are substituted with the blank sentinel and NEVER left as empty
    // text that could masquerade as real data (never silent empty — Requirement 3.4).
    // Validates: Requirements 3.3, 3.4
    // ------------------------------------------------------------------------------------------

    @Property(tries = 300)
    @Tag("Feature: FOR-05-08-document-signing, Property 6: merge resolution is deterministic with reported unresolved placeholders")
    void resolvedTokensSubstitutedUnresolvedBlankedNeverSilentEmpty(
            @ForAll("templates") Template template) {
        MergeResult result = engine.render(template.body(), context, MergeMode.MARK_BLANK);
        String body = result.body();

        // No raw {Token} placeholder for a known token survives in the output — all were handled.
        for (String token : template.tokens()) {
            assertThat(body).doesNotContain("{" + token + "}");
        }

        // Each distinct resolvable token used contributes its exact value (and the body never
        // reduces that value to a blank sentinel or to empty text).
        for (String token : distinct(template.tokens())) {
            if (RESOLVABLE.containsKey(token)) {
                assertThat(body).contains(RESOLVABLE.get(token));
            }
        }

        // If any unresolved token was used, the human-visible blank sentinel appears; if none was,
        // the sentinel never appears (no spurious blanks).
        if (result.unresolvedPlaceholders().isEmpty()) {
            assertThat(body).doesNotContain(BLANK_SENTINEL);
        } else {
            assertThat(body).contains(BLANK_SENTINEL);
        }
    }

    // ------------------------------------------------------------------------------------------
    // Property 6d: FAIL mode is deterministic and reports every unresolved token — it throws the
    // 422 with the sorted unresolved list iff the template has any unresolvable token, and succeeds
    // with no unresolved set otherwise. The MARK_BLANK unresolved set and the FAIL throw/no-throw
    // decision agree on the same template.
    // Validates: Requirements 3.4, 3.8
    // ------------------------------------------------------------------------------------------

    @Property(tries = 300)
    @Tag("Feature: FOR-05-08-document-signing, Property 6: merge resolution is deterministic with reported unresolved placeholders")
    void failModeThrowsIffAnyUnresolvedAndIsDeterministic(@ForAll("templates") Template template) {
        MergeResult blankRun = engine.render(template.body(), context, MergeMode.MARK_BLANK);
        boolean hasUnresolved = !blankRun.unresolvedPlaceholders().isEmpty();

        if (hasUnresolved) {
            assertThatThrownBy(() -> engine.render(template.body(), context, MergeMode.FAIL))
                    .isInstanceOfSatisfying(ForemenApiException.class, ex -> {
                        assertThat(ex.getStatus()).isEqualTo(HttpStatus.UNPROCESSABLE_ENTITY);
                        assertThat(ex.getMessageCode()).isEqualTo(UNRESOLVED_MESSAGE);
                        // The message param lists exactly the unresolved tokens, sorted.
                        List<String> sorted = new ArrayList<>(blankRun.unresolvedPlaceholders());
                        sorted.sort(String::compareTo);
                        assertThat(ex.getMessageParams()).containsExactly(String.join(", ", sorted));
                    });
        } else {
            // Fully resolvable: FAIL mode succeeds, reports no unresolved tokens, and leaves no
            // blank sentinel (every token was substituted with a real value).
            MergeResult failRun = engine.render(template.body(), context, MergeMode.FAIL);
            assertThat(failRun.unresolvedPlaceholders()).isEmpty();
            assertThat(failRun.body()).isEqualTo(blankRun.body());
            assertThat(failRun.body()).doesNotContain(BLANK_SENTINEL);
        }
    }

    private static List<String> distinct(List<String> tokens) {
        return new ArrayList<>(new LinkedHashSet<>(tokens));
    }

    // ------------------------------------------------------------------------------------------
    // Fake resolver: a controllable MergeFieldResolver that supports exactly the RESOLVABLE and
    // SUPPORTED_BUT_NULL tokens, maps the former to values and the latter to null, and claims no
    // other token. It ignores the MergeContext entirely so the properties test the engine's merge
    // behaviour in isolation.
    // ------------------------------------------------------------------------------------------

    private static final class FakeResolver implements MergeFieldResolver {
        @Override
        public boolean supports(String token) {
            return RESOLVABLE.containsKey(token) || SUPPORTED_BUT_NULL.contains(token);
        }

        @Override
        public String resolve(String token, MergeContext ctx) {
            // RESOLVABLE -> value; SUPPORTED_BUT_NULL -> null (unresolved). supports() guarantees the
            // token is one of these two.
            return RESOLVABLE.get(token);
        }
    }

    // ------------------------------------------------------------------------------------------
    // Generators
    // ------------------------------------------------------------------------------------------

    /**
     * A generated template: the raw body text and the ordered list of placeholder tokens it embeds
     * (so the test oracle knows the token stream without re-parsing the body).
     */
    record Template(String body, List<String> tokens) {
    }

    /**
     * Arbitrary templates interleaving literal segments with {@code {Token}} placeholders drawn from
     * the resolvable pool and the two unresolvable pools, so every render mixes substituted and
     * unresolved tokens (including repeated tokens and templates with no placeholders at all).
     */
    @Provide
    Arbitrary<Template> templates() {
        return segments().list().ofMinSize(0).ofMaxSize(10).map(this::assemble);
    }

    /**
     * A single template segment: either a literal text run (brace-free so it cannot be mistaken for
     * a placeholder) or a placeholder token.
     */
    private Arbitrary<Segment> segments() {
        Arbitrary<Segment> literals = literalText().map(Segment::literal);
        Arbitrary<Segment> placeholders = tokenNames().map(Segment::placeholder);
        // Weight placeholders a little heavier so most templates carry at least one token.
        return Arbitraries.oneOf(literals, placeholders, placeholders);
    }

    /** Brace-free literal text (letters, digits, spaces, a few punctuation marks). */
    private Arbitrary<String> literalText() {
        return Arbitraries.strings()
                .withChars("abcdefghijklmnopqrstuvwxyz ABCDEF0123456789.,;:-\n")
                .ofMinLength(0)
                .ofMaxLength(12);
    }

    /** Any token name from the three pools (resolvable, supported-but-null, unsupported). */
    private Arbitrary<String> tokenNames() {
        List<String> all = new ArrayList<>(RESOLVABLE.keySet());
        all.addAll(SUPPORTED_BUT_NULL);
        all.addAll(UNSUPPORTED);
        return Arbitraries.of(all);
    }

    private Template assemble(List<Segment> segments) {
        StringBuilder body = new StringBuilder();
        List<String> tokens = new ArrayList<>();
        for (Segment segment : segments) {
            if (segment.token() != null) {
                body.append('{').append(segment.token()).append('}');
                tokens.add(segment.token());
            } else {
                body.append(segment.literal());
            }
        }
        return new Template(body.toString(), tokens);
    }

    /** A template segment: exactly one of {@code literal} or {@code token} is non-null. */
    private record Segment(String literal, String token) {
        static Segment literal(String text) {
            return new Segment(text, null);
        }

        static Segment placeholder(String token) {
            return new Segment(null, token);
        }
    }
}
