spring:
  profiles:
    active: local
  liquibase:
    change-log: classpath:database_files/changelog.xml

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs

foremen:
  cache:
    spec: "maximumSize=500,expireAfterWrite=10m"
  cors:
    allowed-origins: "http://localhost:3000"
