package com.foremen.service.document;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.List;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;

import com.foremen.dao.model.DocumentFormFieldEntity;
import com.foremen.dao.model.SignableDocumentEntity;
import com.foremen.exception.ForemenApiException;
import com.foremen.service.document.pdf.InMemoryMultipartFile;
import com.foremen.service.document.pdf.PdfRenderer;
import com.foremen.service.image.ImageStorage;

import lombok.RequiredArgsConstructor;

/**
 * FOR-05-08 (Requirements 1.5, 3.6): the PDF-freeze service — renders a {@code SignableDocument}'s
 * current DRAFT body (including its declared {@link DocumentFormFieldEntity form fields} as fillable
 * regions) into the canonical, immutable signing artifact, stores it in object storage, and returns
 * its reference + content hash.
 *
 * <p>Called <b>exactly once</b>, on {@code request-signatures} (the {@code DRAFT →
 * PENDING_SIGNATURES} transition): the service builds a self-contained XHTML of the body + form
 * fields, renders it to a canonical PDF via the {@link PdfRenderer} seam (the sole place the
 * concrete HTML→PDF library lives — swappable without touching the lifecycle), stores the PDF bytes
 * through the same shared {@link ImageStorage} seam {@code DocumentMediaService} uses (FOR-12), and
 * computes the sha-256 of the exact stored bytes. The returned {@link FrozenArtifact} carries
 * {@code storageUri} + {@code contentHash}; from that moment the artifact is byte-immutable and the
 * {@code contentHash} is the integrity anchor for {@code ONLINE}/{@code PODPIS_GOV_PL} verification
 * (R6.4; NFR 5).
 */
@Service
@RequiredArgsConstructor
public class PdfFreezeService {

    /** Namespace under which frozen signing PDFs are stored in object storage (FOR-12). */
    private static final String STORAGE_NAMESPACE = "signable-documents";

    /** Content type of the stored frozen artifact. */
    private static final String PDF_CONTENT_TYPE = "application/pdf";

    /** 500 when the sha-256 digest provider is unexpectedly unavailable. */
    private static final String HASH_FAILED = "error.document.hash.failed";

    private final PdfRenderer pdfRenderer;
    private final ImageStorage objectStorage;

    /**
     * Freeze the document's current body into its canonical immutable PDF: render → store → hash.
     *
     * @param doc the document being sent for signatures; its body + declared form fields are frozen
     * @return the stored artifact's object-storage reference and sha-256 content hash
     */
    public FrozenArtifact freeze(SignableDocumentEntity doc) {
        if (doc == null) {
            throw new ForemenApiException(HttpStatus.INTERNAL_SERVER_ERROR, "error.document.render.failed");
        }

        String xhtml = buildCanonicalXhtml(doc);
        byte[] pdfBytes = pdfRenderer.renderToPdf(xhtml);

        // Compute the sha-256 over the EXACT bytes that are stored, so the hash is a faithful
        // integrity anchor for the stored artifact (R1.5, R6.4).
        String contentHash = sha256Hex(pdfBytes);

        // Store the frozen PDF through the same shared object-storage seam DocumentMediaService
        // uses (FOR-12); the server-generated bytes are wrapped as an in-memory MultipartFile since
        // the seam is defined in terms of MultipartFile and there is no HTTP upload to forward.
        InMemoryMultipartFile upload = new InMemoryMultipartFile(
                "file", frozenFileName(doc), PDF_CONTENT_TYPE, pdfBytes);
        String storageUri = objectStorage.store(upload, STORAGE_NAMESPACE);

        return new FrozenArtifact(storageUri, contentHash);
    }

    /**
     * Build a self-contained, well-formed XHTML of the document's current body and its declared form
     * fields rendered as fillable regions (a labelled underline per field) — the canonical content
     * the frozen PDF is rendered from (R1.5, R3.6).
     */
    private String buildCanonicalXhtml(SignableDocumentEntity doc) {
        StringBuilder html = new StringBuilder(1024);
        html.append("<!DOCTYPE html>")
                .append("<html><head><meta charset=\"utf-8\"/>")
                .append("<style>")
                .append("body{font-family:sans-serif;font-size:12px;margin:40px;}")
                .append("h1{font-size:18px;}")
                .append(".form-field{margin:8px 0;}")
                .append(".form-field .blank{display:inline-block;min-width:200px;")
                .append("border-bottom:1px solid #000;}")
                .append("</style></head><body>");

        String typeCode = doc.getDocumentType() != null ? doc.getDocumentType().getCode() : null;
        html.append("<h1>").append(escape(resolveTitle(doc, typeCode))).append("</h1>");
        if (typeCode != null) {
            html.append("<p>").append(escape(typeCode)).append("</p>");
        }

        appendFormFields(html, doc.getFormFields());

        html.append("</body></html>");
        return html.toString();
    }

    /**
     * Render each declared form field as a fillable region: label + its filled value (if any) over
     * an underlined blank, so the frozen artifact carries the fillable layout (R3.6). A {@code null}
     * or empty field list contributes nothing.
     */
    private void appendFormFields(StringBuilder html, List<DocumentFormFieldEntity> formFields) {
        if (formFields == null || formFields.isEmpty()) {
            return;
        }
        html.append("<div class=\"form-fields\">");
        for (DocumentFormFieldEntity field : formFields) {
            if (field == null) {
                continue;
            }
            String label = field.getLabel() != null && !field.getLabel().isBlank()
                    ? field.getLabel()
                    : field.getKey();
            String value = field.getValue() != null ? field.getValue() : "";
            html.append("<div class=\"form-field\">")
                    .append(escape(label)).append(": ")
                    .append("<span class=\"blank\">").append(escape(value)).append("</span>")
                    .append("</div>");
        }
        html.append("</div>");
    }

    private String resolveTitle(SignableDocumentEntity doc, String typeCode) {
        if (doc.getTitle() != null && !doc.getTitle().isBlank()) {
            return doc.getTitle();
        }
        return typeCode != null ? typeCode : "Document";
    }

    private String frozenFileName(SignableDocumentEntity doc) {
        Long id = doc.getId();
        return "frozen-document-" + (id != null ? id : "new") + ".pdf";
    }

    /** Compute the lowercase hex sha-256 of the given bytes. */
    private String sha256Hex(byte[] bytes) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(bytes);
            StringBuilder hex = new StringBuilder(hash.length * 2);
            for (byte b : hash) {
                hex.append(Character.forDigit((b >> 4) & 0xF, 16));
                hex.append(Character.forDigit(b & 0xF, 16));
            }
            return hex.toString();
        } catch (NoSuchAlgorithmException e) {
            // SHA-256 is a mandated JDK algorithm; this is defensive and should be unreachable.
            throw new ForemenApiException(HttpStatus.INTERNAL_SERVER_ERROR, HASH_FAILED);
        }
    }

    /** Minimal XML/HTML text escaping for the canonical body so arbitrary field text is safe. */
    private String escape(String text) {
        if (text == null) {
            return "";
        }
        return text.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }
}
